FROM uhub.service.ucloud.cn/ainnovation/golang:1.20-bullseye as builder

RUN apt-get install make

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env 

WORKDIR /build
# Build the binary
COPY . .
RUN make -C scheduler -o test-go build-scheduler

# Kafka dependencies necessitate leaving CGo enabled and using a base image with C dependencies
FROM registry.access.redhat.com/ubi9/ubi-micro:9.3-15
COPY --from=builder /build/scheduler/bin/scheduler /bin/scheduler

# Copy licenses
COPY scheduler/licenses/ /licenses/
COPY components/tls/licenses/ /licenses/seldontls/

ENTRYPOINT ["/bin/scheduler"]
