FROM uhub.service.ucloud.cn/ainnovation/golang:1.20-alpine as builder

WORKDIR /build

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env 
RUN apk add --no-cache make

COPY . .

# Build the binary
RUN make -C scheduler -o test-go build-agent

# Copy binary
FROM registry.access.redhat.com/ubi9/ubi-micro:9.3-15

RUN mkdir /mnt/agent && chmod o+rwx /mnt/agent
VOLUME /mnt/agent

COPY --from=builder /build/scheduler/bin/agent /bin/agent

# Copy licenses
COPY scheduler/licenses/ /licenses/
COPY components/tls/licenses/ /licenses/seldontls/

ENTRYPOINT ["/bin/agent"]
