disableAutoUpdate: false
seldonConfig: default

hodometer:
  disable: true
  replicas: 1
  
scheduler:
  disable: false
  replicas: 1
  # controlplane exposure
  serviceType: ClusterIP
  
envoy:
  disable: false
  replicas: 1
  # dataplane exposure
  serviceType: LoadBalancer 
  
dataflow:
  disable: true
  replicas: 1
  
modelgateway:
  disable: true
  replicas: 1
  
pipelinegateway:
  disable: true
  replicas: 1

config:
  agentConfig:
    rclone:
      configSecrets:
  kafkaConfig:
    bootstrap:
    topicPrefix:
    consumer:
    producer:
    streams:
  tracingConfig:
    disable: true
    otelExporterEndpoint:
    otelExporterProtocol:
    ratio:
  serviceConfig:
    serviceGRPCPrefix:
    serviceType:
  
